harmony:
  input_select:
    living_room_tv:
      name: Living Room TV
      icon: mdi:television
      options:
        - Watch TV
        - Watch Apple TV
        - Play PS4
      initial: Watch TV

  sensor:
  - platform: template
    sensors:
      living_room_tv:
        friendly_name: 'Living Room TV'
        value_template: >
          {% if is_state("binary_sensor.living_room_tv.state", "off") -%}
            PowerOff
          {%- else -%}
            {{ states.remote.living_room_tv.attributes.current_activity }}
          {%- endif %}

  switch:
  - platform: template
    switches:
      living_room_tv:
        friendly_name: Living Room TV
        value_template: '{{ states.sensor.living_room_tv.state != "PowerOff" }}'
        entity_id: sensor.living_room_tv
        turn_on:
          service:  remote.turn_on
          data_template:
            entity_id: remote.living_room_tv
            activity: '{{ states.input_select.living_room_tv.state }}'
        turn_off:
          service: remote.turn_off
          entity_id: remote.living_room_tv

  remote:
  - platform: harmony
    name: Harmony Hub
    scan_interval: 5

  binary_sensor:
  - platform: ping
    host: 10.0.1.30
    name: 'Harmony Hub'

  - platform: template
    living_room_hdmi:
      friendly_name: 'Living Room HDMI'
      value_template: >-
        {{ states.sensor.living_room_tv.state != 'PowerOff' and
           states.sensor.living_room_tv.state != 'Watch TV'
        }}

  automation:
  - alias: Harmony Change Activity
    trigger:
    - platform: state
      entity_id: input_select.living_room_tv
    action:
    - service: remote.turn_on
      data_template:
        entity_id: remote.living_room_tv
        activity: '{{ states.input_select.living_room_tv.state }}'

  - alias: Harmony Update Activity Select
    trigger:
    - platform: state
      entity_id: sensor.living_room_tv
    condition:
      condition: template
      value_template: '{{ states.sensor.living_room_tv.state != "PowerOff" and states.sensor.living_room_tv.state != "None" }}'
    action:
    - service: input_select.select_option
      data_template:
        entity_id: input_select.living_room_tv
        option: '{{ states.sensor.living_room_tv.state }}'
