hyperion:
  automation:
  - alias: Hyperion Sync
    trigger:
    - platform: state
      entity_id: sensor.living_room_hdmi
    - platform: state
      entity_id: input_select.hyperion_effect
    - platform: state
      entity_id: sensor.day_phase
    - platform: state
      entity_id: input_boolean.light.living_room
    action:
    - service_template: >
          {% if states.sensor.living_room_hdmi.state == 'on' %}
            shell_command.hyperion_ambilight
          {% elif states.light.living_room.state == 'on'
            and states.sensor.day_phase.state in ['Evening', 'Night'] %}
            shell_command.hyperion_standby
          {% else %}
            shell_command.hyperion_off
          {% endif %}


#  input_select:
#    hyperion_effect:
#      name: TV Ambilight Effect
#      icon: mdi:camcorder-box
#      options:
#      - "None"
#      - "Knight rider"
#      - "Full color mood blobs"
#      - "Rainbow mood"
#      - "Blue mood blobs"
#      - "Cold mood blobs"
#      - "Green mood blobs"
#      - "Red mood blobs"
#      - "Warm mood blobs"
#      - "Rainbow swirl fast"
#      - "Snake"
#      - "Strobe blue"
#      - "Strobe Raspbmc"
#      - "Strobe white"
#      - "Cinema dim lights"
#      - "Cinema brighten lights"
#      - "Police Lights Single"
#      - "Police Lights Solid"
#      - "Random"
#      - "Running dots"
#      - "System Shutdown"
#      - "Sparks Color"
#      - "Sparks"
#      - "Color traces"
#      initial: "None"

  switch:
  - platform: command_line
    switches:
      hyperion:
        friendly_name: Ambilight
        command_on: '/config/bash_scripts/hyperion/on.sh'
        command_off: '/config/bash_scripts/hyperion/off.sh'
        command_state: '/config/bash_scripts/hyperion/status.sh'

  shell_command:
    hyperion_off: '/config/bash_scripts/hyperion/off.sh'
    hyperion_ambilight: '/config/bash_scripts/hyperion/on.sh'
    hyperion_standby: '/config/bash_scripts/hyperion/effects.sh "Full color mood blobs"'
    hyperion_effect: '/config/bash_scripts/hyperion/effects.sh "{{ states.input_select.hyperion_effect.state }}"'
