language: python
python:
  - '3.4'
install:
  - 'pip3 install homeassistant'
script:
  - 'hass -c ..config --script check_config | tee check.output'
  - '! less check.output | grep -q ERROR'
before_install:
  - 'mv ./config/secrets.yaml.sample ./config/secrets.yaml'
