language: python
python:
  - '3.5'
install:
  - 'pip3 install homeassistant'
script:
  - 'hass -c ./config --script check_config | tee check.output'
  - '! less check.output | grep -q "Failed config"'
before_install:
  - 'mv ./config/secrets.yaml.sample ./config/secrets.yaml'
