homeassistant:
  name: Home
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_long
  elevation: 110
  unit_system: metric
  time_zone: Europe/London

  customize: !include configuration/customize.yaml
  packages: !include_dir_merge_named configuration/packages

# Enablers
cloud:
config:
conversation:
#discovery:
#  ignore:
#    - apple_tv
#    - plex_mediaserver
frontend:
  themes: !include_dir_merge_named themes
hue:
  bridges:
  - host: 192.168.0.116
    allow_unreachable: false
    allow_hue_groups: true
ios:
webostv:
  host: 192.168.0.124
  name: LG TV
mobile_app:

sun:
updater:
  include_used_components: true

# History
recorder:
  purge_interval: 1
  purge_keep_days: 14
  exclude:
    entities:
    - sensor.date
logbook:
  exclude:
    domains:
      - group
    entities:
      - input_boolean.node_red_heartbeat
      - binary_sensor.kitchen_motion
      - binary_sensor.entryway_motion
      - binary_sensor.top_floor_motion
      - sensor.log_db_file_size
      - sensor.cpu_temp
      - sensor.average_load_15m
      - sensor.since_last_boot
      - sensor.replay_kitchen
      - sensor.replay_entryway
      - sensor.replay_top_floor

# external links
#weblink:
#  entities:
#  - name: Travis
#    icon: mdi:worker
#    url: https://travis-ci.org/claytonjdc/Home-Assistant
#  - name: Node Red
#    icon: mdi:sitemap
#    url: https://c4qtytxo2egxsr0rszmpbcomt19r7ezd.ui.nabu.casa/a0d7b954_nodered

# Text to speech
tts:
  - platform: google_translate

# Device Tracking
zone:
  - name: Home
    latitude: !secret zone_home_lat
    longitude: !secret zone_home_long
    radius: 250
  
  - name: Work
    latitude: !secret zone_work_lat
    longitude: !secret zone_work_long
    radius: 500

#http:
  # Uncomment this to add a password (recommended!)
  #api_password: !secret hass_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  #base_url: !secret hass_base_url
  #trusted_networks:
  #- 127.0.0.1
  #- 192.168.0.0/24
  #- 10.0.1.0/24

# Components
# automation: !include_dir_merge_list configuration/automation
binary_sensor: !include_dir_merge_list configuration/binary_sensor
group: !include_dir_merge_named configuration/group
# history_graph: !include_dir_merge_named configuration/history_graph
input_boolean: !include_dir_merge_named configuration/input_boolean
nest: !include configuration/nest.yaml
# scene: !include_dir_merge_list configuration/scene
sensor: !include_dir_merge_list configuration/sensor
switch: !include_dir_merge_list configuration/switch
