homeassistant:
  name: Home
  latitude: 50.2601751
  longitude: -5.089021499999944
  elevation: 110
  unit_system: metric
  time_zone: Europe/London

  customize: !include configuration/customize.yaml
  packages: !include_dir_merge_named configuration/packages

http:
  # Uncomment this to add a password (recommended!)
  api_password: !secret hass_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  base_url: hass15wsw.duckdns.org:8123
  trusted_networks:
  - 127.0.0.1
  - 192.168.0.0/24
  - 10.0.1.0/24


# Enablers
config:
conversation:
discovery:
frontend:
ios:
sun:
updater:
  include_used_components: true

recorder:
  purge_interval: 1
  purge_keep_days: 14
  exclude:
    entities:
    - sensor.date
history:
logbook:
  exclude:
    entities:
    - sensor.log_db_file_size
    - sensor.cpu_temp
    - sensor.average_load_15m
    - sensor.since_last_boot

hue:
  bridges:
  - host: 192.168.0.116
    allow_unreachable: false
    allow_hue_groups: true

# Text to speech
tts:
  - platform: google

automation: !include_dir_merge_list configuration/automation
binary_sensor: !include_dir_merge_list configuration/binary_sensor
group: !include_dir_merge_named configuration/group
#input_select: !include_dir_merge_named input_select
nest: !include configuration/nest.yaml
#remote: !include_dir_merge_list remote
scene: !include_dir_merge_list configuration/scene
#script: !include_dir_merge_list script
# shell_command: !include_dir_merge_named shell_command
sensor: !include_dir_merge_list configuration/sensor
switch: !include_dir_merge_list configuration/switch
