- alias: Kitchen Lights Off
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    platform: state
    from: 'on'
    to: 'off'
    for:
      hours: 0
      minutes: 15
      seconds: 0
  action:
  - service: light.turn_off
    entity_id: light.kitchen
    data:
      transition: 15

- alias: Kitchen Lights On
  trigger:
  - entity_id: binary_sensor.kitchen_motion
    platform: state
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: light.kitchen
    state: 'off'
  action:
  - service: hue.hue_activate_scene
    data_template:
      group_name: Kitchen
      scene_name: '{{ states.sensor.day_phase.state }}'

- alias: Kitchen Lights Update
  trigger:
  - entity_id: sensor.day_phase
    platform: state
  condition:
    condition: state
    entity_id: light.kitchen
    state: 'on'
  action:
  - service: hue.hue_activate_scene
    data_template:
      group_name: Kitchen
      scene_name: '{{ states.sensor.day_phase.state }}'
