- platform: template
  switches:
    harmony_hub:
      friendly_name: Living Room TV
      value_template: '{{ states.sensor.harmony_hub.state != "PowerOff" }}'
      entity_id: sensor.harmony_hub
      turn_on:
        service:  remote.turn_on
        data_template:
          entity_id: remote.harmony_hub
          activity: '{{ states.input_select.harmony_hub.state }}'
      turn_off:
        service: remote.turn_off
        entity_id: remote.harmony_hub

- platform: command_line
  switches:
    hyperion:
      friendly_name: TV Ambilight
      command_on: '/config/bash_scripts/hyperion/on.sh'
      command_off: '/config/bash_scripts/hyperion/off.sh'
      command_state: '/config/bash_scripts/hyperion/status.sh'
