- platform: template
  switches:
    harmony_hub:
      friendly_name: Living Room TV
      value_template: '{{ states.remote.harmony_hub.attributes.current_activity != "PowerOff" }}'
      entity_id: sensor.harmony_hub
      turn_on:
        service:  remote.turn_on
        data_template:
          entity_id: remote.harmony_hub
          activity: '{{ states.input_select.harmony_hub.state }}'
      turn_off:
        service: remote.turn_off
        entity_id: remote.harmony_hub
