- platform: template
  sensors:
    harmomy_hub:
      value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
      friendly_name: 'Living Room TV'

- platform: rest
  resource: https://api.travis-ci.org/repos/claytonjdc/hass-config/builds
  headers:
    Accept: application/vnd.travis-ci.2+json
  value_template: '{{ value_json.builds[0].state }}'
  name: 'Travis Build Status'
