- alias: "Harmony Change Activity"
  trigger:
  - platform: state
    entity_id: input_select.harmony_hub
  action:
  - service: remote.turn_on
    data_template:
      entity_id: remote.harmony_hub
      activity: '{{ states.input_select.harmony_hub.state }}'

- alias: "Harmony Update Activity Select"
  trigger:
  - platform: state
    entity_id: sensor.harmony_hub
  condition:
    condition: template
    value_template: '{{ states.remote.harmony_hub.attributes.current_activity != "PowerOff" and states.remote.harmony_hub.attributes.current_activity != "None" }}'
  action:
  - service: input_select.select_option
    data_template:
      entity_id: input_select.harmony_hub
      option: '{{ states.remote.harmony_hub.attributes.current_activity }}'
