- alias: Hyperion No Effect
  trigger:
  - platform: state
    entity_id: input_select.hyperion_effect
    to: "None"
  action:
    service: shell_command.hyperion_effect_none

- alias: Hyperion Set Effect
  trigger:
  - platform: state
    entity_id: input_select.hyperion_effect
    from: "None"
  action:
    service: shell_command.hyperion_set_effect

- alias: Hyperion Auto On
  trigger:
  - platform: state
    entity_id: sensor.living_room_tv
    from: "PowerOff"
  action:
    service: switch.turn_on
    entity_id: switch.hyperion

- alias: Hyperion Auto Off
  trigger:
  - platform: state
    entity_id: sensor.living_room_tv
    to: "PowerOff"
  action:
    service: switch.turn_off
    entity_id: switch.hyperion
