- platform: huesensor
#  ip_address: 192.168.0.116
#  token: !secret hue_token

#- platform: template
#  sensors:
#    kitchen_light:
#      friendly_name: 'Kitchen Light'
#      unit_of_measurement: Lux
#      value_template: '{{ states.binary_sensor.kitchen_sensor_motion.attributes.light_level }}'

    # kitchen_temperature:
    #   friendly_name: 'Kitchen Temperature'
    #   unit_of_measurement: °C
    #   value_template: '{{ states.binary_sensor.kitchen_sensor_motion.attributes.temperature }}'

    # entryway_light:
    #   friendly_name: 'Entryway Light'
    #   unit_of_measurement: Lux
    #   value_template: '{{ states.binary_sensor.entryway_sensor_motion.attributes.light_level }}'

    # entryway_temperature:
    #   friendly_name: 'Entryway Temperature'
    #   unit_of_measurement: °C
    #   value_template: '{{ states.binary_sensor.entryway_sensor_motion.attributes.temperature }}'

    # top_floor_light:
    #   friendly_name: 'Top Floor Light'
    #   unit_of_measurement: Lux
    #   value_template: '{{ states.binary_sensor.top_floor_sensor_motion.attributes.light_level }}'

    # top_floor_temperature:
    #   friendly_name: 'Top Floor Temperature'
    #   unit_of_measurement: °C
    #   value_template: '{{ states.binary_sensor.top_floor_sensor_motion.attributes.temperature }}'