#- platform: huesensor

- platform: template
  sensors:
    kitchen_light:
      friendly_name: 'Kitchen Light'
      unit_of_measurement: Lux
      value_template: '{{ states.sensor.kitchen_sensor_light_level.attributes.lightlevel }}'

    entryway_light:
      friendly_name: 'Entryway Light'
      unit_of_measurement: Lux
      value_template: '{{ states.sensor.entryway_sensor_light_level.attributes.lightlevel }}'
  
    middle_floor_light:
      friendly_name: 'Middle Floor Light'
      unit_of_measurement: Lux
      value_template: '{{ states.sensor.middle_floor_sensor_light_level.attributes.lightlevel }}'

    top_floor_light:
      friendly_name: 'Top Floor Light'
      unit_of_measurement: Lux
      value_template: '{{ states.sensor.top_floor_sensor_light_level.attributes.lightlevel }}'

    # top_floor_temperature:
    #   friendly_name: 'Top Floor Temperature'
    #   unit_of_measurement: °C
    #   value_template: '{{ states.binary_sensor.top_floor_sensor_motion.attributes.temperature }}'