- platform: rest
  resource: https://api.travis-ci.org/repos/claytonjdc/Home-Assistant/builds
  headers:
    Accept: application/vnd.travis-ci.2+json
  value_template: '{{ value_json.builds[0].state }}'
  name: 'Travis Build Status'

- platform: template
  sensors:
    lights_on:
      friendly_name: "Lights On"
      unit_of_measurement: "Count"
      value_template: >
        {{ states.light
            | selectattr('state', 'eq', 'on')
            | rejectattr('attributes.is_hue_group')
            | list 
            | count
        }}
    rooms_on:
      friendly_name: "Rooms On"
      unit_of_measurement: "Count"
      value_template: >
        {{ states.light
            | selectattr('state', 'eq', 'on')
            | selectattr('attributes.is_hue_group')
            | list 
            | count
        }}