light.dining_room:
  icon: mdi:lightbulb-outline

light.hallway:
  icon: mdi:lightbulb-outline

light.kitchen:
  icon: mdi:lightbulb-outline

light.living_room:
  icon: mdi:lightbulb-outline

light.master_bedroom:
  icon: mdi:lightbulb-outline

light.office:
  icon: mdi:lightbulb-outline

switch.living_room_tv:
  icon: mdi:television

switch.hyperion:
    icon: mdi:camcorder-box
