- platform: command_line
  switches:
    hyperion:
      friendly_name: Ambilight
      command_on: '/config/bash_scripts/hyperion/on.sh'
      command_off: '/config/bash_scripts/hyperion/off.sh'
      command_state: '/config/bash_scripts/hyperion/status.sh'