default_view:
  name: Home
  view: yes
  entities:
  - device_tracker.bones
  - sensor.scotty_battery_level
  - sensor.chekov_battery_level
  - sensor.day_phase
  - group.house_climate
  - group.meta_rooms
  - group.short_weather
  - scene.indie_chillout

living_room:
  name: Living Room
  icon: mdi:sofa
  view: yes
  entities:
  - group.living_room_lights
  - group.living_room_tv
  - group.living_room_this_week
  - group.living_room_last_week
  - media_player.living_room

kitchen:
  name: Kitchen
  icon: mdi:food-variant
  view: yes
  entities:
  - sensor.kitchen_temperature
  - sensor.kitchen_light
  - binary_sensor.kitchen_motion
  - group.kitchen_lights
  - media_player.kitchen

bedroom:
  name: Bedroom
  icon: mdi:hotel
  view: yes
  entities:
    - media_player.bedroom
    - light.master_bedroom

lights:
  name: Lights
  icon: mdi:lightbulb
  view: yes
  entities:
  - group.bedroom_lights
  - group.dining_room_lights
  - group.hallway_lights
  - group.kitchen_lights
  - group.living_room_lamp
  - group.living_room_lights
  - group.office_lights

media:
  name: Media
  icon: mdi:movie
  view: yes
  entities:
  - group.sonos
  - group.tv

house:
  name: House
  icon: mdi:home-modern
  view: yes
  entities:
  - group.house_climate
  - group.house_other
  - group.network
  - group.smoke_detector
  - group.devices

outside:
  name: Outside
  icon: mdi:weather-partlycloudy
  view: yes
  entities:
  - group.misc_weather
  - group.dark_sky
  - group.met_office
