living_room_tv:
  name: TV
  icon: mdi:television
  entities:
  - switch.living_room_tv
  - input_select.living_room_tv
  - switch.hyperion
  - input_select.hyperion_effect
  - media_player.apple_tv
  - remote.apple_tv
