living_room_tv:
  name: TV
  icon: mdi:television
  entities:
  - switch.harmony_hub
  - input_select.harmony_hub
  - switch.hyperion
  - input_select.hyperion_effect
  - media_player.apple_tv
  - remote.apple_tv

living_room_this_week:
  name: Activity This Week
  entities:
  - sensor.total_tv_watched_this_week
  - sensor.tv_watched_this_week
  - sensor.apple_tv_watched_this_week

living_room_last_week:
  name: Activity Last Week
  entities:
  - sensor.total_tv_watched_last_week
  - sensor.tv_watched_last_week
  - sensor.apple_tv_watched_last_week
