living_room_tv:
  name: TV
  icon: mdi:television
  entities:
  - switch.harmony_hub
  - input_select.harmony_hub
  - switch.hyperion
  - input_select.hyperion_effect
  - media_player.apple_tv
  - remote.apple_tv
