speakers:
  name: Sonos
  icon: mdi:speaker
  entities:
  - media_player.kitchen
  - media_player.living_room
  - media_player.bedroom

tv:
  name: TV
  icon: mdi:television
  entities:
  - media_player.apple_tv
  - remote.apple_tv
