meta_rooms:
  name: Rooms
  icon: mdi:home-variant
  entities:
  - group.bedroom_lights
  - group.dining_room_lights
  - group.hallway_lights
  - group.kitchen_lights
  - group.living_room_lamp
  - group.office_lights
