misc_weather:
  name: Weather
  entities:
  - sun.sun
  - sensor.moon
  # - sensor.yr_symbol

dark_sky:
  name: Dark Sky
  entities:
  - sensor.dark_sky_minutely_summary
  - sensor.dark_sky_summary
  - sensor.dark_sky_daily_max_precip_intensity
  - sensor.dark_sky_precip
  - sensor.dark_sky_precip_intensity
  - sensor.dark_sky_precip_probability
  - sensor.dark_sky_nearest_storm_distance

met_office:
  name: Met Office
  entities:
  - sensor.met_office_weather
  - sensor.met_office_temperature
  - sensor.met_office_feels_like_temperature
  - sensor.met_office_humidity
  - sensor.met_office_uv
  - sensor.met_office_visibility
  - sensor.met_office_wind_direction
  - sensor.met_office_wind_gust
  - sensor.met_office_wind_speed
