- alias: "Action Motion Disable On"
  initial_state: false
  trigger:
    - platform: event
      event_type: ios.action_fired
      event_data:
        actionName: 'Disable Motion'
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.motion_disable