- platform: template
  sensors:
    kitchen_motion:
      friendly_name: 'Kitchen Motion'
      value_template: >
        {{ states.sensor.kitchen_motion_sensor.state == 'on' }}

    entryway_motion:
      friendly_name: 'Entryway Motion'
      value_template: >
        {{ states.sensor.motion_entryway_sensor.state == 'on' }}