- platform: template
  sensors:
    occupied:
      friendly_name: "Occupied"
      value_template: >
        {{ 
          states.device_tracker.jphone.state == "home" or
          states.sensor.recent_motion.state|float > 0
        }}
    
    house_motion:
      friendly_name: "House Motion"
      value_template: >
        {{ 
          states.binary_sensor.entryway_sensor_motion.state == 'on' or
          states.binary_sensor.kitchen_sensor_motion.state == 'on' or
          states.binary_sensor.middle_floor_sensor_motion.state == 'on' or
          states.binary_sensor.top_floor_sensor_motion.state == 'on'
        }}